version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  web:
    build: ./web
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000 
    volumes:
      - ./web:/code
    depends_on:
      - db
    restart: always
    
volumes:
  postgres:
