# Generated by Django 4.1.1 on 2022-10-11 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='posts',
            new_name='post',
        ),
    ]
